name: Raw Bank Scraper

on:

  workflow_dispatch:

  schedule:
    - cron: "10 0 * * *"
    - cron: "10 12 * * *"

permissions:
  contents: write

jobs:

  scrape:

    runs-on: ubuntu-latest

    timeout-minutes: 360

    steps:

      # =====================================
      # CHECKOUT
      # =====================================

      - name: Checkout repository
        uses: actions/checkout@v4

      # =====================================
      # PYTHON
      # =====================================

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # =====================================
      # INSTALL
      # =====================================

      - name: Install packages
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps chromium

      # =====================================
      # RUN SCRIPT
      # =====================================

      - name: Run scraper
        run: |
          python main.py

      # =====================================
      # COMMIT JSON
      # =====================================

      - name: Commit JSON files
        run: |

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add *.json
          git add raw_banks/*.json

          git commit -m "🤖 Auto update raw bank data" || echo "No changes"

          git pull --rebase

          git push
