name: Alif Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        env:
          FIRECRAWL_API: ${{ secrets.FIRECRAWL_API }}
        run: python banks/alif/main.py
