name: test

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    env:
      FIRECRAWL_API: ${{ secrets.FIRECRAWL_API }}
      OPENROUTER_API: ${{ secrets.OPENROUTER_API }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        run: python banks/alif/main.py
